<?php
/*-------------------------------------------------------+
| PHPFusion Content Management System
| Copyright (C) PHP Fusion Inc
| https://phpfusion.com/
+--------------------------------------------------------+
| Filename: English.php
| Author: RobiNN
+--------------------------------------------------------+
| This program is released as free software under the
| Affero GPL license. You can redistribute it and/or
| modify it under the terms of this license which you
| can read by viewing the included agpl.txt or online
| at www.gnu.org/licenses/agpl.html. Removal of this
| copyright header is strictly prohibited without
| written permission from the original author(s).
+--------------------------------------------------------*/
$locale['rc3_title'] = 'reCAPTCHA v3';
$locale['rc3_desc'] = 'reCAPTCHA v3 returns a score for each request without user friction.';
$locale['rc3_01'] = 'Settings has been updated';
$locale['rc3_02'] = 'Register and obtain your [LINK]keys here[/LINK].';
$locale['rc3_03'] = 'Site Key';
$locale['rc3_04'] = 'Secret Key';
$locale['rc3_05'] = 'Score';
$locale['rc3_06'] = 'Recaptcha will rank traffic and interactions based on a score of 0.0 to 1.0, with a 1.0 being a good interaction and scores closer to 0.0 indicating a good likelihood that the traffic was generated by bots. Setting this value too high could potentially block legitimate users.';
