<?php
/*-------------------------------------------------------+
| PHP-Fusion Content Management System
| Copyright (C) PHP Fusion Inc
| https://www.phpfusion.com/
+--------------------------------------------------------+
| Filename: functions.php
| Author: RobiNN
+--------------------------------------------------------+
| This program is released as free software under the
| Affero GPL license. You can redistribute it and/or
| modify it under the terms of this license which you
| can read by viewing the included agpl.txt or online
| at www.gnu.org/licenses/agpl.html. Removal of this
| copyright header is strictly prohibited without
| written permission from the original author(s).
+--------------------------------------------------------*/
defined('IN_FUSION') || exit;

/**
 * @return string Unique token
 */
function random_token() {
    return md5(uniqid(rand(), TRUE));
}

/**
 * @param string $subject  The Subject of the message
 * @param string $body     An HTML or plain text message body
 * @param string $email    The email address to send to
 * @param int    $priority Email priority: 3 = normal, 2 = low, 1 = high
 * @param string $token    Token generated by random_token()
 * @param string $style    Custom CSS
 *
 * @return array
 * @throws \PHPMailer\PHPMailer\Exception
 */
function send_newsletter($subject, $body, $email, $priority, $token, $style = NULL) {
    $locale = fusion_get_locale('', NSL_LOCALE);
    $settings = fusion_get_settings();
    $nsl_settings = get_settings('newsletter_panel');

    require_once CLASSES.'PHPMailer/PHPMailer.php';
    require_once CLASSES.'PHPMailer/Exception.php';
    require_once CLASSES.'PHPMailer/SMTP.php';

    $m = new PHPMailer\PHPMailer\PHPMailer();

    if ($nsl_settings['add_dkim'] == 1) {
        $m->DKIM_domain = $nsl_settings['dkim_domain'];
        $m->DKIM_private_string = $nsl_settings['dkim_private'];
        $m->DKIM_selector = $nsl_settings['dkim_selector'];
        $m->DKIM_passphrase = $nsl_settings['dkim_passphrase'];
        $m->DKIM_identity = $nsl_settings['dkim_identity'];
    }

    if ($nsl_settings['how_to_send'] == 'smtp') {
        $m->IsSMTP();
        $m->SMTPKeepAlive = TRUE;

        $servers = [];
        $result = dbquery("SELECT * FROM ".DB_NEWSLETTER_SMTP." WHERE smtp_active=1");
        if (dbrows($result) > 0) {
            while ($smtp = dbarray($result)) {
                $servers[] = $smtp;
            }
        }

        $server = $servers[array_rand($servers)];

        if (isset($server['smtp_host']) && isset($server['smtp_port'])) {
            $m->Host = $server['smtp_host'];
            $m->Port = $server['smtp_port'];

            if (!empty($server['smtp_name']) && $server['smtp_pass']) {
                $m->SMTPAuth = TRUE;
                $m->Username = $server['smtp_name'];
                $m->Password = $server['smtp_pass'];
            } else {
                $m->SMTPAuth = FALSE;
            }

            if ($server['smtp_secure'] !== 'no') {
                $m->SMTPSecure = $server['smtp_secure'];
            }

            $m->Timeout = $server['smtp_timeout'];
        }

    } else if ($nsl_settings['how_to_send'] == 'sendmail' && $nsl_settings['sendmail_path'] != '') {
        $m->IsSendmail();
        $m->Sendmail = $nsl_settings['sendmail_path'];
    } else {
        $m->IsMail();
    }

    $m->CharSet = $nsl_settings['charset'];

    if ($priority == 1) {
        $m->Priority = 1;
    } else if ($priority == 2) {
        $m->Priority = 5;
    } else {
        $m->Priority = 3;
    }

    if ($nsl_settings['show_email'] == 0) {
        $from = 'noreply@'.$settings['site_host'];
    } else {
        $from = $nsl_settings['sender_email'];
    }

    $m->setFrom($from, $nsl_settings['sender_name']);
    $m->isHTML($nsl_settings['content_type'] == 'html');
    $m->Subject = $subject;
    $m->AddAddress($email);

    $result = dbquery("SELECT * FROM ".DB_NEWSLETTER_HEADERS);
    if (dbrows($result) > 0) {
        while ($header = dbarray($result)) {
            $m->addCustomHeader($header['header_name'].': '.$header['header_value']);
        }
    }

    $unsubscribe_text = $locale['nsl_053'].' ';
    if (!empty($token)) {
        if (check_nsl_seo()) {
            $unsubscribe = $settings['siteurl'].'newsletter/unsubscribe/'.$token;
        } else {
            $unsubscribe = $settings['siteurl'].'infusions/newsletter_panel/newsletter.php?unsubscribe='.$token;
        }

        $m->addCustomHeader('List-Unsubscribe: '.$unsubscribe);

        $unsubscribe_text .= str_replace(['[LINK]', '[/LINK]'], ['<a href="'.$unsubscribe.'" target="_blank">', '</a>'], $locale['nsl_054']);
    } else {
        $unsubscribe_text .= str_replace('[LINK]', '<a href="'.$settings['siteurl'].'" target="_blank">'.$settings['sitename'].'</a>', $locale['nsl_055']);
    }

    if ($nsl_settings['content_type'] == 'html') {
        $html = '<!DOCTYPE html>
        <html>
        <head>
            <meta name="viewport" content="width=device-width">
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <title>[TITLE]</title>
            <style type="text/css">[STYLE]</style>
        </head>
        <body>[CONTENT]</body>
        </html>';

        $body = str_replace(
            ['[CONTENT]', '[STYLE]'],
            [htmlspecialchars_decode($body), htmlspecialchars_decode($style)],
            $html
        );
    }

    $body = strtr($body, [
        '[TITLE]'          => $subject,
        '[LOGO]'           => $settings['siteurl'].$settings['sitebanner'],
        '[SITENAME]'       => $settings['sitename'],
        '[SITEURL]'        => $settings['siteurl'],
        '[SITE_COPYRIGHT]' => nl2br(parse_textarea($settings['footer'], FALSE, TRUE)),
        '[EMAIL]'          => $email,
        '[UNSUBSCRIBE]'    => $unsubscribe_text
    ]);

    $m->Body = $body;

    if (!$m->Send()) {
        $result = ['result' => FALSE, 'error' => $m->ErrorInfo];
    } else {
        $result = ['result' => TRUE, 'error' => NULL];
    }

    $m->ClearCustomHeaders();
    $m->ClearAllRecipients();

    if ($nsl_settings['how_to_send'] == 'smtp') {
        $m->SmtpClose();
    }

    return $result;
}

function check_nsl_seo() {
    $rows = dbcount("(rewrite_id)", DB_PERMALINK_REWRITE, "rewrite_name=:rwname", [':rwname' => 'newsletter']);

    if (fusion_get_settings('site_seo') && $rows == 1) {
        return TRUE;
    }

    return FALSE;
}
